// Code generated by toy compiler v0.5 on Thu Dec 14 09:46:21 2017
#include <toy-runtime.h>

// ----------------------------------------
// Class Point implementation
// ----------------------------------------

typedef struct Point *Point; // class Point implementation typedef
struct Point {
  _toy_metaclass *_instance_of;
  int _Point_x, _Point_y;
};

extern _toy_metaclass _toy_meta_Point; // fully declared below

Point _init_Point(Point this) { // Point class constructor
  _init_Object((Object) this);
  this->_instance_of = &_toy_meta_Point;

  this->_Point_x = 0;
  this->_Point_y = 0;
  return this;
}

// Methods of the class Point

void _Point_printobj(Point this) {
  {
    printf("%s", "(");
    printf("%d", _TOY_ACCESS(this,Point)->_Point_x);
    printf("%s", ", ");
    printf("%d", _TOY_ACCESS(this,Point)->_Point_y);
    printf("%s", ")");
    fflush(stdout);
  }
}

Point _Point_init(Point this, int x, int y) {
  _TOY_ACCESS(this,Point)->_Point_x = x;
  _TOY_ACCESS(this,Point)->_Point_y = y;
  return (Point)(this);
}

void _Point_readobj(Point this) {
  {
    printf("%s", "Value of x? ");
    fflush(stdout);
  }
  {
    _toy_read_int(&_TOY_ACCESS(this,Point)->_Point_x);
    fflush(stdout);
  }
  {
    printf("%s", "Value of y? ");
    fflush(stdout);
  }
  {
    _toy_read_int(&_TOY_ACCESS(this,Point)->_Point_y);
    fflush(stdout);
  }
}

// Point metaclass declaration
_toy_metaclass _toy_meta_Point = {
     .classname    = "Point",
     .extends_meta = &_toy_meta_Object,
     .methods      = {
        _Point_printobj,
        _Object_typename,
        _Point_init,
        _Point_readobj}
};

// ---- End of class Point

char isatty(int fd);
int main(void) {
  Point p1 = (Point)(_TOY_INVOKE(Point, _init_Point(_TOY_NEW(Point)), 2, _this, 1, 2));
  Point p2 = (Point)(_init_Point(_TOY_NEW(Point)));
  {
    printf("%s", "Point p1: ");
    _toy_print_object((Object) p1);
    printf("%s", "\n");
    fflush(stdout);
  }
  {
    printf("%s", "Enter coordinates of point p2\n");
    fflush(stdout);
  }
  {
    _toy_read_object((Object) p2);
    fflush(stdout);
  }
  if (!(isatty(0)))
    {
      {
        printf("%s", (_TOY_ACCESS(p2,Point)->_Point_x == 12 && _TOY_ACCESS(p2,Point)->_Point_y == 34) ? "\nSUCCESS\n" : "\nFAILURE\n");
        fflush(stdout);
      }
    }
  {
    printf("%s", "Point p2: ");
    _toy_print_object((Object) p2);
    printf("%s", "\n");
    fflush(stdout);
  }
  return 0;
}
