syntax.h: syntax.y
lexical.c: syntax.h
analysis.o: analysis.c toy.h ast.h ../lib/list.h utils.h symbols.h \
 analysis.h
main.o: main.c toy.h ast.h ../lib/list.h syntax.h prodcode.h symbols.h
prodcode.o: prodcode.c toy.h ast.h ../lib/list.h prodcode.h
ast.o: ast.c toy.h ast.h ../lib/list.h analysis.h prodcode.h utils.h
symbols.o: symbols.c ../lib/hash.h toy.h ast.h ../lib/list.h utils.h \
 symbols.h
utils.o: utils.c toy.h ast.h ../lib/list.h utils.h
